<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarcTime.Core\MarcTime.Core.csproj" />
    <ProjectReference Include="..\MarcTime.Data\MarcTime.Data.csproj" />
  </ItemGroup>

</Project>
